variable "vpc_id" {}
variable "subnet1" {}
variable "subnet2" {}
variable "subnet3" {}
variable "cluster_name" {}
variable "environment" {}
variable "instance_type" {}
variable "asg_max_size" {}
variable "asg_min_size" {}
variable "cluster_version" {}
