environment = "dev"
s3_bucket = "amazon-eks-dev-ahmet"   #Will be used to set backend.tf
s3_folder_project = "application"          #Will be used to set backend.tf
s3_folder_region = "us-west-2"             #Will be used to set backend.tf
s3_folder_type = "state"                   #Will be used to set backend.tf
s3_tfstate_file = "infrastructure.tfstate" #Will be used to set backend.tf
vpc_id = "vpc-6d076c05"
subnet1 = "subnet-03f34a79"
subnet2 = "subnet-c01ed28c"
subnet3 = "subnet-2508754c"
cluster_name = "dev-cluster"
instance_type = "t2.micro"
asg_max_size = "48" 
asg_desired_capacity = "3"
asg_min_size = "3"
cluster_version = "1.14"
region = "us-west-2"
