environment = "stage"
s3_bucket = "amazon-eks-stage-team4"   #Will be used to set backend.tf
s3_folder_project = "application"          #Will be used to set backend.tf
s3_folder_region = "us-east-1"             #Will be used to set backend.tf
s3_folder_type = "state"                   #Will be used to set backend.tf
s3_tfstate_file = "infrastructure.tfstate" #Will be used to set backend.tf
vpc_id = "vpc-1471ad6e"
subnet1 = ""
subnet2 = ""
subnet3 = ""
cluster_name = "stage-cluster"
